; Font is https://managore.itch.io/m6x11 by Daniel Linssen
; Generated via python/ttf_export.py, and then MmWw manually shortened

SECTION "Charmap", ROMX, BANK[TEXT_BANK], ALIGN[8]

MACRO Charmap_Register
    SETCHARMAP TALL
    CHARMAP \1, \2
    SETCHARMAP TALL_WIDTH
    CHARMAP \1, \3
    db \3
ENDM

NEWCHARMAP TALL
CHARMAP "🛑", $FF
NEWCHARMAP TALL_WIDTH
CHARMAP "🛑", $FF

Charmap_EOL EQU $FF

Charmap_Width::
    Charmap_Register "!", $00, $03
    Charmap_Register "\"", $01, $06
    Charmap_Register "#", $02, $08
    Charmap_Register "$", $03, $07
    Charmap_Register "%", $04, $07
    Charmap_Register "&", $05, $08
    Charmap_Register "'", $06, $03
    Charmap_Register "(", $07, $05
    Charmap_Register ")", $08, $05
    Charmap_Register "*", $09, $06
    Charmap_Register "+", $0A, $07
    Charmap_Register ",", $0B, $03
    Charmap_Register "-", $0C, $07
    Charmap_Register ".", $0D, $03
    Charmap_Register "/", $0E, $07
    Charmap_Register "0", $0F, $07
    Charmap_Register "1", $10, $07
    Charmap_Register "2", $11, $07
    Charmap_Register "3", $12, $07
    Charmap_Register "4", $13, $07
    Charmap_Register "5", $14, $07
    Charmap_Register "6", $15, $07
    Charmap_Register "7", $16, $07
    Charmap_Register "8", $17, $07
    Charmap_Register "9", $18, $07
    Charmap_Register ":", $19, $03
    Charmap_Register ";", $1A, $03
    Charmap_Register "<", $1B, $06
    Charmap_Register "=", $1C, $07
    Charmap_Register ">", $1D, $06
    Charmap_Register "?", $1E, $07
    Charmap_Register "@", $1F, $08
    Charmap_Register "A", $20, $07
    Charmap_Register "B", $21, $07
    Charmap_Register "C", $22, $07
    Charmap_Register "D", $23, $07
    Charmap_Register "E", $24, $07
    Charmap_Register "F", $25, $07
    Charmap_Register "G", $26, $07
    Charmap_Register "H", $27, $07
    Charmap_Register "I", $28, $07
    Charmap_Register "J", $29, $07
    Charmap_Register "K", $2A, $07
    Charmap_Register "L", $2B, $07
    Charmap_Register "M", $2C, $08
    Charmap_Register "N", $2D, $07
    Charmap_Register "O", $2E, $07
    Charmap_Register "P", $2F, $07
    Charmap_Register "Q", $30, $08
    Charmap_Register "R", $31, $07
    Charmap_Register "S", $32, $07
    Charmap_Register "T", $33, $07
    Charmap_Register "U", $34, $07
    Charmap_Register "V", $35, $07
    Charmap_Register "W", $36, $08
    Charmap_Register "X", $37, $08
    Charmap_Register "Y", $38, $07
    Charmap_Register "Z", $39, $07
    Charmap_Register "[", $3A, $05
    Charmap_Register "\\", $3B, $07
    Charmap_Register "]", $3C, $05
    Charmap_Register "^", $3D, $07
    Charmap_Register "_", $3E, $07
    Charmap_Register "a", $3F, $07
    Charmap_Register "b", $40, $07
    Charmap_Register "c", $41, $07
    Charmap_Register "d", $42, $07
    Charmap_Register "e", $43, $07
    Charmap_Register "f", $44, $07
    Charmap_Register "g", $45, $07
    Charmap_Register "h", $46, $07
    Charmap_Register "i", $47, $03
    Charmap_Register "j", $48, $05
    Charmap_Register "k", $49, $07
    Charmap_Register "l", $4A, $03
    Charmap_Register "m", $4B, $08
    Charmap_Register "n", $4C, $07
    Charmap_Register "o", $4D, $07
    Charmap_Register "p", $4E, $07
    Charmap_Register "q", $4F, $07
    Charmap_Register "r", $50, $07
    Charmap_Register "s", $51, $07
    Charmap_Register "t", $52, $07
    Charmap_Register "u", $53, $07
    Charmap_Register "v", $54, $07
    Charmap_Register "w", $55, $08
    Charmap_Register "x", $56, $08
    Charmap_Register "y", $57, $07
    Charmap_Register "z", $58, $07
    Charmap_Register "\{", $59, $06
    Charmap_Register "|", $5A, $03
    Charmap_Register "}", $5B, $06
    Charmap_Register "~", $5C, $07
    Charmap_Register " ", $5D, $05
    Charmap_Register "¡", $5E, $03
    Charmap_Register "¢", $5F, $07
    Charmap_Register "£", $60, $08
    Charmap_Register "¤", $61, $08
    Charmap_Register "¥", $62, $07
    Charmap_Register "¦", $63, $03
    Charmap_Register "§", $64, $07
    Charmap_Register "¨", $65, $06
    Charmap_Register "©", $66, $08
    Charmap_Register "ª", $67, $04
    Charmap_Register "«", $68, $08
    Charmap_Register "¬", $69, $07
    Charmap_Register "®", $6A, $08
    Charmap_Register "°", $6B, $06
    Charmap_Register "±", $6C, $07
    Charmap_Register "²", $6D, $04
    Charmap_Register "³", $6E, $04
    Charmap_Register "´", $6F, $03
    Charmap_Register "µ", $70, $07
    Charmap_Register "¶", $71, $08
    Charmap_Register "¹", $72, $04
    Charmap_Register "º", $73, $04
    Charmap_Register "»", $74, $08
    Charmap_Register "¿", $75, $07
    Charmap_Register "×", $76, $07
    Charmap_Register "÷", $77, $07
SETCHARMAP TALL

SECTION "Charmap Width", ROMX, BANK[TEXT_BANK], ALIGN[8]
wText_Font::
    INCBIN "autogenerated/assets/Font.tileset"