; Font is https://managore.itch.io/m6x11 by Daniel Linssen
; Generated via python/ttf_export.py, and then MmWw manually shortened

MACRO Charmap_Register
    IF STRCMP(\1, "NONE") != 0
        ; Register the Char if it is not NONE
        SETCHARMAP CHAR
        CHARMAP \1, \2
        SETCHARMAP WIDTH
        CHARMAP \1, \3
    ENDC
    ; We must always register a width for alignment
    db \3
ENDM

NEWCHARMAP CHAR
NEWCHARMAP WIDTH

ALIGN 8
Charmap_Width::
    Charmap_Register "NONE", $00, $FF
    Charmap_Register "NONE", $01, $FF
    Charmap_Register "NONE", $02, $FF
    Charmap_Register "NONE", $03, $FF
    Charmap_Register "NONE", $04, $FF
    Charmap_Register "NONE", $05, $FF
    Charmap_Register "NONE", $06, $FF
    Charmap_Register "NONE", $07, $FF
    Charmap_Register "NONE", $08, $FF
    Charmap_Register "NONE", $09, $FF
    Charmap_Register "NONE", $0A, $FF
    Charmap_Register "NONE", $0B, $FF
    Charmap_Register "NONE", $0C, $FF
    Charmap_Register "NONE", $0D, $FF
    Charmap_Register "NONE", $0E, $FF
    Charmap_Register "NONE", $0F, $FF
    Charmap_Register "NONE", $10, $FF
    Charmap_Register "NONE", $11, $FF
    Charmap_Register "NONE", $12, $FF
    Charmap_Register "NONE", $13, $FF
    Charmap_Register "NONE", $14, $FF
    Charmap_Register "NONE", $15, $FF
    Charmap_Register "NONE", $16, $FF
    Charmap_Register "NONE", $17, $FF
    Charmap_Register "NONE", $18, $FF
    Charmap_Register "NONE", $19, $FF
    Charmap_Register "NONE", $1A, $FF
    Charmap_Register "NONE", $1B, $FF
    Charmap_Register "NONE", $1C, $FF
    Charmap_Register "NONE", $1D, $FF
    Charmap_Register "NONE", $1E, $FF
    Charmap_Register "NONE", $1F, $FF
    Charmap_Register " ", $20, $05
    Charmap_Register "!", $21, $03
    Charmap_Register "\"", $22, $06
    Charmap_Register "#", $23, $08
    Charmap_Register "$", $24, $07
    Charmap_Register "%", $25, $07
    Charmap_Register "&", $26, $08
    Charmap_Register "'", $27, $03
    Charmap_Register "(", $28, $05
    Charmap_Register ")", $29, $05
    Charmap_Register "*", $2A, $06
    Charmap_Register "+", $2B, $07
    Charmap_Register ",", $2C, $03
    Charmap_Register "-", $2D, $07
    Charmap_Register ".", $2E, $03
    Charmap_Register "/", $2F, $07
    Charmap_Register "0", $30, $07
    Charmap_Register "1", $31, $07
    Charmap_Register "2", $32, $07
    Charmap_Register "3", $33, $07
    Charmap_Register "4", $34, $07
    Charmap_Register "5", $35, $07
    Charmap_Register "6", $36, $07
    Charmap_Register "7", $37, $07
    Charmap_Register "8", $38, $07
    Charmap_Register "9", $39, $07
    Charmap_Register ":", $3A, $03
    Charmap_Register ";", $3B, $03
    Charmap_Register "<", $3C, $06
    Charmap_Register "=", $3D, $07
    Charmap_Register ">", $3E, $06
    Charmap_Register "?", $3F, $07
    Charmap_Register "@", $40, $08
    Charmap_Register "A", $41, $07
    Charmap_Register "B", $42, $07
    Charmap_Register "C", $43, $07
    Charmap_Register "D", $44, $07
    Charmap_Register "E", $45, $07
    Charmap_Register "F", $46, $07
    Charmap_Register "G", $47, $07
    Charmap_Register "H", $48, $07
    Charmap_Register "I", $49, $07
    Charmap_Register "J", $4A, $07
    Charmap_Register "K", $4B, $07
    Charmap_Register "L", $4C, $07
    Charmap_Register "M", $4D, $08
    Charmap_Register "N", $4E, $07
    Charmap_Register "O", $4F, $07
    Charmap_Register "P", $50, $07
    Charmap_Register "Q", $51, $08
    Charmap_Register "R", $52, $07
    Charmap_Register "S", $53, $07
    Charmap_Register "T", $54, $07
    Charmap_Register "U", $55, $07
    Charmap_Register "V", $56, $07
    Charmap_Register "W", $57, $08
    Charmap_Register "X", $58, $08
    Charmap_Register "Y", $59, $07
    Charmap_Register "Z", $5A, $07
    Charmap_Register "[", $5B, $05
    Charmap_Register "\\", $5C, $07
    Charmap_Register "]", $5D, $05
    Charmap_Register "^", $5E, $07
    Charmap_Register "_", $5F, $07
    Charmap_Register "NONE", $60, $FF
    Charmap_Register "a", $61, $07
    Charmap_Register "b", $62, $07
    Charmap_Register "c", $63, $07
    Charmap_Register "d", $64, $07
    Charmap_Register "e", $65, $07
    Charmap_Register "f", $66, $07
    Charmap_Register "g", $67, $07
    Charmap_Register "h", $68, $07
    Charmap_Register "i", $69, $03
    Charmap_Register "j", $6A, $05
    Charmap_Register "k", $6B, $07
    Charmap_Register "l", $6C, $03
    Charmap_Register "m", $6D, $08
    Charmap_Register "n", $6E, $07
    Charmap_Register "o", $6F, $07
    Charmap_Register "p", $70, $07
    Charmap_Register "q", $71, $07
    Charmap_Register "r", $72, $07
    Charmap_Register "s", $73, $07
    Charmap_Register "t", $74, $07
    Charmap_Register "u", $75, $07
    Charmap_Register "v", $76, $07
    Charmap_Register "w", $77, $08
    Charmap_Register "x", $78, $08
    Charmap_Register "y", $79, $07
    Charmap_Register "z", $7A, $07
    Charmap_Register "\{", $7B, $06
    Charmap_Register "|", $7C, $03
    Charmap_Register "}", $7D, $06
    Charmap_Register "~", $7E, $07
    Charmap_Register "NONE", $7F, $FF
    Charmap_Register "NONE", $80, $FF
    Charmap_Register "NONE", $81, $FF
    Charmap_Register "NONE", $82, $FF
    Charmap_Register "NONE", $83, $FF
    Charmap_Register "NONE", $84, $FF
    Charmap_Register "NONE", $85, $FF
    Charmap_Register "NONE", $86, $FF
    Charmap_Register "NONE", $87, $FF
    Charmap_Register "NONE", $88, $FF
    Charmap_Register "NONE", $89, $FF
    Charmap_Register "NONE", $8A, $FF
    Charmap_Register "NONE", $8B, $FF
    Charmap_Register "NONE", $8C, $FF
    Charmap_Register "NONE", $8D, $FF
    Charmap_Register "NONE", $8E, $FF
    Charmap_Register "NONE", $8F, $FF
    Charmap_Register "NONE", $90, $FF
    Charmap_Register "NONE", $91, $FF
    Charmap_Register "NONE", $92, $FF
    Charmap_Register "NONE", $93, $FF
    Charmap_Register "NONE", $94, $FF
    Charmap_Register "NONE", $95, $FF
    Charmap_Register "NONE", $96, $FF
    Charmap_Register "NONE", $97, $FF
    Charmap_Register "NONE", $98, $FF
    Charmap_Register "NONE", $99, $FF
    Charmap_Register "NONE", $9A, $FF
    Charmap_Register "NONE", $9B, $FF
    Charmap_Register "NONE", $9C, $FF
    Charmap_Register "NONE", $9D, $FF
    Charmap_Register "NONE", $9E, $FF
    Charmap_Register "NONE", $9F, $FF
    Charmap_Register "NONE", $A0, $FF
    Charmap_Register "¡", $A1, $03
    Charmap_Register "¢", $A2, $07
    Charmap_Register "£", $A3, $08
    Charmap_Register "¤", $A4, $08
    Charmap_Register "¥", $A5, $07
    Charmap_Register "¦", $A6, $03
    Charmap_Register "§", $A7, $07
    Charmap_Register "¨", $A8, $06
    Charmap_Register "©", $A9, $08
    Charmap_Register "ª", $AA, $04
    Charmap_Register "«", $AB, $08
    Charmap_Register "¬", $AC, $07
    Charmap_Register "NONE", $AD, $FF
    Charmap_Register "®", $AE, $08
    Charmap_Register "NONE", $AF, $FF
    Charmap_Register "°", $B0, $06
    Charmap_Register "±", $B1, $07
    Charmap_Register "²", $B2, $04
    Charmap_Register "³", $B3, $04
    Charmap_Register "´", $B4, $03
    Charmap_Register "µ", $B5, $07
    Charmap_Register "¶", $B6, $08
    Charmap_Register "NONE", $B7, $FF
    Charmap_Register "NONE", $B8, $FF
    Charmap_Register "¹", $B9, $04
    Charmap_Register "º", $BA, $04
    Charmap_Register "»", $BB, $08
    Charmap_Register "NONE", $BC, $FF
    Charmap_Register "NONE", $BD, $FF
    Charmap_Register "NONE", $BE, $FF
    Charmap_Register "¿", $BF, $07
    Charmap_Register "NONE", $C0, $FF
    Charmap_Register "NONE", $C1, $FF
    Charmap_Register "NONE", $C2, $FF
    Charmap_Register "NONE", $C3, $FF
    Charmap_Register "NONE", $C4, $FF
    Charmap_Register "NONE", $C5, $FF
    Charmap_Register "NONE", $C6, $FF
    Charmap_Register "NONE", $C7, $FF
    Charmap_Register "NONE", $C8, $FF
    Charmap_Register "NONE", $C9, $FF
    Charmap_Register "NONE", $CA, $FF
    Charmap_Register "NONE", $CB, $FF
    Charmap_Register "NONE", $CC, $FF
    Charmap_Register "NONE", $CD, $FF
    Charmap_Register "NONE", $CE, $FF
    Charmap_Register "NONE", $CF, $FF
    Charmap_Register "NONE", $D0, $FF
    Charmap_Register "NONE", $D1, $FF
    Charmap_Register "NONE", $D2, $FF
    Charmap_Register "NONE", $D3, $FF
    Charmap_Register "NONE", $D4, $FF
    Charmap_Register "NONE", $D5, $FF
    Charmap_Register "NONE", $D6, $FF
    Charmap_Register "×", $D7, $07
    Charmap_Register "NONE", $D8, $FF
    Charmap_Register "NONE", $D9, $FF
    Charmap_Register "NONE", $DA, $FF
    Charmap_Register "NONE", $DB, $FF
    Charmap_Register "NONE", $DC, $FF
    Charmap_Register "NONE", $DD, $FF
    Charmap_Register "NONE", $DE, $FF
    Charmap_Register "NONE", $DF, $FF
    Charmap_Register "NONE", $E0, $FF
    Charmap_Register "NONE", $E1, $FF
    Charmap_Register "NONE", $E2, $FF
    Charmap_Register "NONE", $E3, $FF
    Charmap_Register "NONE", $E4, $FF
    Charmap_Register "NONE", $E5, $FF
    Charmap_Register "NONE", $E6, $FF
    Charmap_Register "NONE", $E7, $FF
    Charmap_Register "NONE", $E8, $FF
    Charmap_Register "NONE", $E9, $FF
    Charmap_Register "NONE", $EA, $FF
    Charmap_Register "NONE", $EB, $FF
    Charmap_Register "NONE", $EC, $FF
    Charmap_Register "NONE", $ED, $FF
    Charmap_Register "NONE", $EE, $FF
    Charmap_Register "NONE", $EF, $FF
    Charmap_Register "NONE", $F0, $FF
    Charmap_Register "NONE", $F1, $FF
    Charmap_Register "NONE", $F2, $FF
    Charmap_Register "NONE", $F3, $FF
    Charmap_Register "NONE", $F4, $FF
    Charmap_Register "NONE", $F5, $FF
    Charmap_Register "NONE", $F6, $FF
    Charmap_Register "÷", $F7, $07
    Charmap_Register "NONE", $F8, $FF
    Charmap_Register "NONE", $F9, $FF
    Charmap_Register "NONE", $FA, $FF
    Charmap_Register "NONE", $FB, $FF
    Charmap_Register "NONE", $FC, $FF
    Charmap_Register "NONE", $FD, $FF
    Charmap_Register "NONE", $FE, $FF
    Charmap_Register "NONE", $FF, $FF