INCLUDE "source/system/banks.asm"
INCLUDE "source/system/call.asm"

INCLUDE "source/system/dma.asm"
INCLUDE "source/system/interrupt.asm"
INCLUDE "source/system/joypad.asm"
INCLUDE "source/system/lcd.asm"
INCLUDE "source/system/math.asm"
INCLUDE "source/system/mem.asm"
INCLUDE "source/system/oam.asm"
INCLUDE "source/system/palette.asm"
INCLUDE "source/system/speed.asm"
INCLUDE "source/system/stack.asm"
INCLUDE "source/system/unpack.asm"