import os
import shutil


# This module deletes the autogenerated assets folder

folders = [
    "autogenerated/assets",
    ]

for folder in folders:
    if os.path.exists(folder):
        shutil.rmtree(folder)
